name: Terraform Dev CI/CD

on:
  push:
    paths:
      - "dev-module/**"
  pull_request:
    branches:
      - dev
    paths:
      - "dev-module/**"
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    name: Terraform Dev Deployment
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dev-module

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Terraform Version
        run: terraform -v

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/') || github.event.inputs.action == 'plan'
        run: terraform plan -var-file=dev.tfvars

      - name: Terraform Apply
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev' || github.event.inputs.action == 'apply'
        run: terraform apply -var-file=dev.tfvars -auto-approve

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -var-file=dev.tfvars -auto-approve
